### ISSUE TITLE
Error build on ubuntu 22 aarch64

### ISSUE THREAD

**Issue by Martos** [rdbo/libmem#211]
Hi, i tried to build with ubuntu 22.04 on AARCH64 but i get this error:
[ 53%] Building C object CMakeFiles/libmem.dir/src/linux/ptrace/ptrace.c.o
/home/user/libmem/src/linux/ptrace/ptrace.c:28:10: fatal error: sys/reg.h: No such file or directory
   28 | #include <sys/reg.h>
      |          ^~~~~~~~~~~
compilation terminated.

Maybe i forgot some params on make ?
Thanks
